spring:
  cloud:
    gateway:
      routes:
        - id: query_baidu
          uri: http://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: query_qq
          uri: http://www.qq.com
          predicates:
            - Query=url, qq
# 低级路由放前面
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
# 高级路由放后面
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
# renrenfast前端项目,api
# http://localhost:88/api/captcha.jpg  http://localhost:8080/renren-fast/captcha.jpg
