spring:
  cloud:
    gateway:
      routes:
        - id: query_baidu
          uri: http://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: query_qq
          uri: http://www.qq.com
          predicates:
            - Query=url, qq